name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout to Branch
        uses: actions/checkout@master
      - name: Install Dependencies
        uses: yarn 
      - name: Build Project
        uses: yarn build
      - name: Activate Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  
